'use strict';
const $=id=>document.getElementById(id);let session=null,library={models:[],instances:[],palette:[]},boards=[],status={state:{}},model=null,instance=null,rear=true,zoom=1,queue=Promise.resolve(),requests=new Map(),serial=0,previewColours=null,lastActivity=performance.now(),lastPoll=0;
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==parent||e.data?.type!=='pixeltool-result')return;const p=requests.get(e.data.id);if(!p)return;requests.delete(e.data.id);e.data.error?p.reject(Error(e.data.error)):p.resolve(e.data.result);});
async function api(op,data={}){if(!session&&['model_save','instance_save','remove'].includes(op))await ensureSession();return new Promise((resolve,reject)=>{const id=++serial;const timer=setTimeout(()=>{requests.delete(id);reject(Error('HA bridge timed out'));},40000);requests.set(id,{resolve:r=>{clearTimeout(timer);resolve(r);},reject:e=>{clearTimeout(timer);reject(e);}});parent.postMessage({type:'pixeltool-api',id,payload:{op,data,session}},location.origin);});}
function action(fn){queue=queue.catch(()=>{}).then(async()=>{try{$('error').textContent='';await fn();}catch(e){if(session&&/Session absent, expired or owned/i.test(e.message)){session=null;instance=null;model=null;previewColours=null;try{status=await api('status');}catch(_){status={...status,output_unknown:true};}renderStatus();}else if(/unavailable|timed out|request failed|Failed to fetch|unconfirmed/i.test(e.message)){status={...status,output_unknown:true};renderStatus();}$('error').textContent=e.message;} });return queue;}
function options(id,items,name){const value=$(id).value;$(id).replaceChildren();items.forEach(x=>$(id).add(new Option(name(x),x.id)));if(items.some(x=>x.id===value))$(id).value=value;}
async function refresh(){library=await api('library');boards=await api('boards');options('model',library.models,m=>m.title+' · '+m.count+' nodes');options('instance',library.instances,i=>i.name);options('board',boards.filter(b=>b.pixel_output&&b.online),b=>b.name+' · '+b.model);showModel();showBoard();}
function showModel(){const m=library.models.find(x=>x.id===$('model').value);if(!m)return;$('title').value=m.title;$('checkpointText').value=m.checkpoints.map(p=>`${p.node},${p.colour},${p.label},${p.confirmed===true}`).join('\n');}
function showBoard(){const b=boards.find(x=>x.id===$('board').value);$('outputs').textContent=b?.outputs.map(o=>`Port ${o.port}: ${o.pixels} configured pixels; ${o.models.map(m=>m.name).join(', ')}`).join(' · ')||'No verified pixel controller';}
function modes(){const tool=$('tool').value;const names=tool==='pusher'?['Colour runs','White + markers','Focus run','Locate pixel','Red','Green','Blue']:['Off','Strand cutter','Manual model guide','Pixel finder','Automatic walk','Inclusive range','Solid red','Solid green','Solid blue','Solid white','Rainbow','Scan','RGB wipe'];$('mode').replaceChildren();names.forEach((n,i)=>$('mode').add(new Option(n,i)));$('pusher').hidden=tool!=='pusher';$('tools').hidden=tool!=='tools';}
function renderStatus(){const s=status.state;const unknown=status.native_stop_uncertain||status.output_unknown;$('status').className=status.armed||status.native_active||unknown?'armed':'';$('status').textContent=unknown?'OUTPUT STATE UNCONFIRMED · check board UI':status.armed||status.native_active?`PIXEL OUTPUT ACTIVE · session ${status.expires_in}s`:`Output disarmed · ${status.session_active?'session '+status.expires_in+'s':'no session'}`;$('nativeTest').disabled=!$('instance').value||boards.find(b=>b.id===instance?.board_id)?.kind==='esp';$('selection').textContent=instance?`${boards.find(b=>b.id===instance.board_id)?.name||instance.board_id} · ${instance.name} · ${model?.title} · ${instance.segments.map(x=>`port ${x.port}, pixel ${x.start_pixel}, nodes ${x.node}–${x.node+x.count-1}`).join('; ')}`:'Select a saved instance and validate its assignment';if(status.error)$('error').textContent=status.error;if(!model)return;const cp=model.checkpoints[s.run||0];$('current').textContent=cp?`${cp.id} · ${cp.node}–${cp.end} · ${cp.label}`:'';}
function elt(tag,attrs,parentEl=$('map')){const e=document.createElementNS('http://www.w3.org/2000/svg',tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));parentEl.append(e);return e;}
function draw(){if(!model)return;const svg=$('map');svg.replaceChildren();const xs=model.coords.map(p=>p[0]),ys=model.coords.map(p=>p[1]);const minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),scale=model.displayXScale||1;svg.setAttribute('viewBox',`-7 -7 ${(maxX-minX)*scale+14} ${maxY-minY+14}`);svg.style.width=zoom*100+'%';const point=n=>{const [x,y]=model.coords[n-1];return [(rear?maxX-x:x-minX)*scale,y-minY];};const data={palette:library.palette.map(rgb=>({rgb})),models:[model]},state={...status.state,model:0,enabled:true,first:instance?.first||1,level:Math.min(status.state.level||12,status.state.cap||12)};
for(let n=1;n<model.count;n++){const a=point(n),b=point(n+1);elt('line',{x1:a[0],y1:a[1],x2:b[0],y2:b[1],stroke:'#41516b','stroke-width':.25});}
model.coords.forEach((_,i)=>{const n=i+1,[x,y]=point(n),cp=model.checkpoints[runForNode(model,n)],marker=cp.node===n;const rgb=status.state.tool==='tools'&&previewColours?previewColours[n-1]:pixelRGB(data,state,n,true),peak=Math.max(...rgb),colour=peak?`rgb(${rgb.map(v=>Math.round(v/peak*(marker?245:145))).join(',')})`:'#2b374c';const c=elt('circle',{cx:x,cy:y,r:marker?1:.7,fill:colour,stroke:marker?'white':'none','stroke-width':.25});elt('title',{},c).textContent=`Node ${n} · ${cp.label}`;c.onclick=()=>action(async()=>{$('node').value=n;await setState({node:n,mode:$('tool').value==='pusher'?3:3});});if(marker||$('numbers').checked)elt('text',{x:x+1,y:y-.8,fill:'#fff','font-size':1.4}).textContent=marker?`${n} ${cp.id}`:n;});$('mapTitle').textContent=model.title+' · '+model.count+' nodes';$('provenance').textContent=model.provenance||'Supplied landmarks; not independently verified physical turns.';$('legend').replaceChildren();library.palette.forEach((rgb,i)=>{const e=document.createElement('span');e.textContent='Colour '+i;e.style.border='3px solid rgb('+rgb.join(',')+')';$('legend').append(e);});$('checkpoints').replaceChildren();model.checkpoints.forEach((p,i)=>{const b=document.createElement('button');b.className='checkpoint';b.textContent=`${p.id} · ${p.node}–${p.end} · ${p.label} ${p.confirmed?'✓':'(unconfirmed)'}`;b.onclick=()=>action(()=>setState({run:i,node:p.node,mode:2}));$('checkpoints').append(b);});}
async function setState(extra={}){await ensureSession();if(!instance)await selectInstance(true);const data={tool:$('tool').value,mode:+$('mode').value,node:+$('node').value,level:+$('level').value,cap:Math.floor(+$('cap').value*255/100),...extra};status=await api('state',data);if(data.tool==='tools'&&data.mode===0){status=await api('stop');}else if(!status.armed){status=await api('arm',{external_output_stopped:true});}previewColours=status.state.tool==='tools'?(await api('preview')).colours:null;$('mode').value=status.state.mode;renderStatus();draw();}
function touch(){lastActivity=performance.now();}
async function ensureSession(){touch();if(!session){const r=await api('claim');session=r.session;status=r;}}
async function stopRelease(){status=await api('stop');if(session){try{status=await api('release');}finally{session=null;}}renderStatus();}
$('stop').onclick=()=>action(stopRelease);$('release').onclick=()=>action(stopRelease);
$('nativeTest').onclick=()=>action(async()=>{await ensureSession();if(!instance)await selectInstance(true);status=await api('state',{level:+$('level').value,cap:Math.floor(+$('cap').value*255/100)});status=await api('native_test',{pattern:$('nativePattern').value,external_output_stopped:true});renderStatus();});
async function selectInstance(preserveControls=false){await ensureSession();status=await api('select',{id:$('instance').value});instance=library.instances.find(i=>i.id===status.selected);model=library.models.find(m=>m.id===instance.model_id);$('model').value=model.id;$('board').value=instance.board_id;$('instanceName').value=instance.name;$('first').value=instance.first||1;$('mapping').value=instance.segments.map(x=>[x.port,x.start_pixel,x.node,x.count].join(',')).join('\n');if(!preserveControls){$('node').max=model.count;$('finish').value=Math.min(50,model.count);$('per').value=Math.min(50,model.count);$('tool').value=status.state.tool;modes();$('mode').value=status.state.mode;$('node').value=status.state.node;$('ends').value=(status.state.ends||[]).join(',');$('level').value=status.state.level;$('cap').value=Math.max(1,Math.round(status.state.cap*100/255));for(const k of ['per','strands','tail','start','finish'])$(k).value=status.state[k];$('walk').value=status.state.walk_ms;}showModel();showBoard();previewColours=status.state.tool==='tools'?(await api('preview')).colours:null;renderStatus();draw();}
$('select').onclick=()=>action(()=>selectInstance());$('instance').onchange=()=>action(async()=>{await stopRelease();instance=null;model=null;previewColours=null;renderStatus();});
$('tool').onchange=()=>{modes();};$('apply').onclick=()=>action(()=>setState($('tool').value==='tools'?{per:+$('per').value,strands:+$('strands').value,tail:+$('tail').value,start:+$('start').value,finish:+$('finish').value,ends:$('ends').value.split(/[ ,;]+/).filter(Boolean).map(Number),walk_ms:+$('walk').value,run:+$('guideSection').value}:{}));$('mode').onchange=()=>action(()=>setState());$('level').onchange=()=>action(()=>setState());$('cap').onchange=()=>action(()=>setState());$('find').onclick=()=>action(()=>setState({mode:3}));$('prevNode').onclick=()=>action(()=>{ $('node').value=Math.max(instance?.first||1,+$('node').value-1);return setState();});$('nextNode').onclick=()=>action(()=>{ $('node').value=Math.min(model.count,+$('node').value+1);return setState();});for(const [id,delta] of [['previous',-1],['next',1]])$(id).onclick=()=>action(()=>{const run=Math.max(0,Math.min(model.checkpoints.length-1,(status.state.run||0)+delta));$('node').value=model.checkpoints[run].node;return setState({run,mode:2});});$('mark').onclick=()=>action(async()=>{await setState();const r=await api('mark');$('markResult').textContent=`Selected ${r.selected}; expected ${r.expected}; difference ${r.difference}. ${r.note}`;});
function uploadFeedback(message,percent=null){$('uploadStatus').textContent=message;$('uploadProgress').hidden=false;if(percent===null)$('uploadProgress').removeAttribute('value');else $('uploadProgress').value=percent;}
function readModelFile(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onprogress=e=>{if(e.lengthComputable)uploadFeedback(`Reading ${file.name} · ${Math.round(e.loaded/e.total*100)}%`,e.loaded/e.total*100);};reader.onload=()=>resolve(new Uint8Array(reader.result));reader.onerror=()=>reject(Error('Could not read the selected file'));reader.onabort=()=>reject(Error('File reading was cancelled'));reader.readAsArrayBuffer(file);});}
async function uploadModel(file){const temporary=!session;try{if(file.size>2097152)throw Error('Maximum upload is 2 MiB');uploadFeedback(`Reading ${file.name}…`,0);const bytes=await readModelFile(file);uploadFeedback('Connecting to PixelTool…');if(temporary){const r=await api('claim');session=r.session;status=r;}let str='';for(const b of bytes)str+=String.fromCharCode(b);uploadFeedback(`Uploading and validating ${file.name}…`);const m=await api('upload',{xml:btoa(str)});instance=null;previewColours=null;uploadFeedback('Model saved. Loading preview…');await refresh();$('model').value=m.id;model=library.models.find(x=>x.id===m.id);showModel();draw();uploadFeedback(`Saved ${m.title} · ${m.count} nodes. Ready to preview.`,100);}catch(e){uploadFeedback(`Upload failed: ${e.message}`,0);throw e;}finally{try{if(temporary&&session){try{status=await api('release');}finally{session=null;}}else if(session){status=await api('status');}}finally{$('upload').disabled=false;$('upload').value='';renderStatus();}}}
$('upload').onchange=()=>{const file=$('upload').files[0];if(!file)return;$('upload').disabled=true;uploadFeedback(`Preparing ${file.name}…`);return action(()=>uploadModel(file));};$('model').onchange=showModel;$('board').onchange=showBoard;$('previewModel').onclick=()=>action(async()=>{if(instance&&instance.model_id!==$('model').value){if(session)status=await api('stop');instance=null;}model=library.models.find(m=>m.id===$('model').value);previewColours=null;renderStatus();draw();});$('rename').onclick=()=>action(async()=>{await api('model_save',{id:$('model').value,title:$('title').value});await refresh();});$('removeModel').onclick=()=>action(async()=>{await api('remove',{kind:'models',id:$('model').value});await refresh();});$('suggest').onclick=()=>{const m=library.models.find(m=>m.id===$('model').value);const starts=[1,...Object.entries(m.sourceStrings||{}).filter(([k])=>/^String\d+$/.test(k)).map(([,v])=>+v)].filter(n=>Number.isInteger(n)&&n>=1&&n<=m.count);$('checkpointText').value=[...new Set(starts)].sort((a,b)=>a-b).map((n,i)=>`${n},${i%library.palette.length},Suggested string start,false`).join('\n');};$('saveCheckpoints').onclick=()=>action(async()=>{const checkpoints=$('checkpointText').value.split('\n').filter(x=>x.trim()).map(l=>{const a=l.split(',');return {node:+a.shift(),colour:+a.shift(),confirmed:a.pop()==='true',label:a.join(',')};});await api('model_save',{id:$('model').value,checkpoints});await refresh();});
function instanceData(id){return {id,name:$('instanceName').value||'Saved prop',model_id:$('model').value,board_id:$('board').value,first:+$('first').value,segments:$('mapping').value.split('\n').filter(x=>x.trim()).map(l=>{const [port,start_pixel,node,count]=l.split(',').map(Number);return {port,start_pixel,node,count};}),progress:{...status.state,node:+$('node').value}};}
$('newInstance').onclick=()=>action(async()=>{const d=instanceData(undefined);delete d.id;await api('instance_save',d);await refresh();});$('updateInstance').onclick=()=>action(async()=>{await api('instance_save',instanceData($('instance').value));await refresh();});$('removeInstance').onclick=()=>action(async()=>{await api('remove',{kind:'instances',id:$('instance').value});await refresh();});$('view').onclick=()=>{rear=!rear;$('view').textContent=rear?'Show front':'Show rear';draw();};$('numbers').onchange=draw;$('zoomIn').onclick=()=>{zoom=Math.min(5,zoom+.5);draw();};$('zoomOut').onclick=()=>{zoom=Math.max(1,zoom-.5);draw();};$('fit').onclick=()=>{zoom=1;draw();};
for(const event of ['pointerdown','keydown','input','change'])document.addEventListener(event,touch,{passive:true});
async function idleTick(){const idleSeconds=(performance.now()-lastActivity)/1000;if(session&&idleSeconds>=(status.idle_timeout||60)){await stopRelease();$('error').textContent='Output stopped and session released after UI inactivity.';return;}if(performance.now()-lastPoll<5000)return;lastPoll=performance.now();status=await api(session?'heartbeat':'status',session?{idle_seconds:idleSeconds}:{});if(session&&!status.session_active)session=null;renderStatus();}
$('idle').onchange=()=>action(async()=>{const temporary=!session;try{await ensureSession();status=await api('preferences_save',{idle_timeout:+$('idle').value});}finally{if(temporary&&session){try{status=await api('release');}finally{session=null;}}renderStatus();}});
setInterval(()=>action(idleTick),1000);window.addEventListener('pagehide',()=>{if(session)api('release').catch(()=>{});});modes();action(async()=>{await refresh();status=await api('status');$('idle').value=status.idle_timeout||60;renderStatus();});
